services:
  dagster:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_CHANNELS=${TELEGRAM_CHANNELS}
      - POSTGRES_USER=week7_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=telegram_db
    volumes:
      - ./photos:/app/photos
      - ./data:/app/data
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=week7_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=telegram_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    environment:
      - POSTGRES_USER=week7_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=telegram_db
    depends_on:
      - postgres
volumes:
  postgres_data: